### ISSUE TITLE
Attribute Error: "CenterFinder" has no attribute 'show kernel'

### ISSUE THREAD

**Issue by jratajcz** [mishtak00/centerfinder#1]
Hello,
   I was running a self made 4-column fits file containing Stripe 82 delta field files. The columns are in the same form as CenterFinder takes as an input.  I run Centerfinder on this fits file using this command: python3 cfdriver.py Stripe82.fits -r 143 -p params_cmassdr9.json -s -v . After running for a bit, I get: Attribute Error: "CenterFinder" has no attribute 'show kernel'. Attached  is the full screenshot of the terminal.
<img width="722" alt="issue1" src="https://user-images.githubusercontent.com/67656617/94644259-cc4f8900-02b6-11eb-9e4d-d6b3e9023b9d.PNG">

**Comment by mishtak00** [comment]
Resolved issue within latest version 👍
