### ISSUE TITLE
Misapplication of over-density correction to empty cells

### ISSUE THREAD

**Issue by zbrown89** [mishtak00/centerfinder#2]
In lines 132-133 of centerfinder.py, the over-density correction is mistakenly applied to empty cells. I fixed it locally by changing L132 to 
`density_grid[density_grid!=0] -= denavg` 
and L133 to 
`density_grid[density_grid!=0] /= denavg`

**Comment by mishtak00** [comment]
Thanks for bringing this up Zack. Fixed!
